image: rust:latest

stages:
  - check
  - test
  - build

variables:
  CARGO_HOME: "$CI_PROJECT_DIR/.cargo"

cache:
  key: "cargo"
  paths:
    - .cargo/
    - target/

check:
  stage: check
  script:
    - rustc --version
    - cargo fmt -- --check
    - cargo clippy -- -D warnings

test:
  stage: test
  script:
    - cargo test

build_wasm:
  stage: build
  script:
    - rustup target add wasm32-wasip2
    - cargo build --release --target wasm32-wasip2
  artifacts:
    paths:
      - target/wasm32-wasip2/release/loom_zed.wasm
    expire_in: 1 week
